system "clear"
system "apt update && apt updgrade"
system "clear"
puts "\n"
puts "~$ Pressione •Enter• Iniciar A Ferramenta•"
puts "\n\n"
a = gets
system "clear"
system "chmod +x tool.rb"
system "ruby tool.rb"
